    version: "3.7"

    services:
        # image project
        frontend:
            image: felipeaguiarphp/book-app-front:latest
            container_name: book-app-frontend
            ports:
                - "8080:80"
            networks:
                - laravel
    networks:
        laravel:
            driver: bridge
